version: "3"

services:
  ms_users_app:
    container_name: ms_users_app
    restart: unless-stopped
    build:
      context: ../
      dockerfile: docker/app/dev.Dockerfile
    environment:
      - APP_ENV=dev
      - LANG=fr_FR.UTF-8
      - PORT=3000
    env_file:
      - app/.env
    ports:
      - 3000:3000
    volumes:
      - "../app:/home/app"
      - "./app/.env:/home/app/.env"
      - "/home/app/node_modules"
    depends_on:
      - ms_users_db
    networks:
      - app-network
      - ms-users-network

  ms_users_db:
    image: postgres
    container_name: ms_users_db
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_PORT=5432
    volumes:
      - db_ms_users_data:/var/lib/postgresql/data
    networks:
      - ms-users-network

volumes:
  db_ms_users_data:

networks:
  app-network:
    external: true
  ms-users-network:
    driver: bridge
